name: Generate SBOM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-sbom:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate SPDX SBOM
      uses: advanced-security/generate-sbom-action@v1
      id: gensbom

    - name: Upload SBOM
      uses: actions/upload-artifact@v3
      with:
        name: sbom
        path: ${{ steps.gensbom.outputs.fileName }}
